a=350
 
if(a<=100):
     print("your electricity bill is ",3*a)
elif(a>100 and a<=200):
     print("your electricity bill is ",a*6)
elif(a>200 and a<=300):
     print("your electricity bill is ",a*20)
elif(a>300 and a<=400):
     print("your electricity bill is ",a*40)
elif(a>400 and a<=500):
     print("your electricity bill is ",a*50)
else:
     print("your use is out of limit")

